# Generated by Django 3.2 on 2022-03-30 15:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newflatpage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной текстовый контент страницы'),
        ),
        migrations.AlterField(
            model_name='newflatpage',
            name='text_block',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Дополнительный блок текста'),
        ),
    ]
